### ISSUE TITLE
Missing file f"{args.wikiart_dir}_csv/artist_class.txt"

### ISSUE THREAD

**Issue by njuaplusplus** [AAAAAAsuka/Impress#2]
https://github.com/AAAAAAsuka/Impress/blob/main/wikiart_preprocessing.py#L89

Could you add this file to this repo or show how to generate the file? Thank you very much.

**Comment by AAAAAAsuka** [comment]
Hi Shengwei,

Sorry for the inconvenience, due to an oversight on my part, I forgot to give the download link for the csv files.

You can download it from this link:
https://drive.google.com/file/d/1uug57zp13wJDwb2nuHOQfR2Odr0hh1a8/view?usp=sharing

I've updated the README.md and wikiart_preprocessing.py to fix this, thanks for the heads up!

**Comment by njuaplusplus** [comment]
Great. Thank you very much.
